# -*- coding: utf-8 -*-
"""Mushroom Classifier App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bU6pk01ab0yy6-sSeqabn5m2AtNQb_zi
"""

import streamlit as st
from PIL import Image
import numpy as np
import tensorflow as tf
import io
import joblib

# --- Configuration ---
# Set the page configuration for the Streamlit app.
# This should be the first Streamlit command in your script.
st.set_page_config(
    page_title="Mushroom Classifier",
    page_icon="🍄",
    layout="centered",
    initial_sidebar_state="auto",
)

# --- Model Loading ---

# IMPORTANT: Make sure your model files are in the same directory as this script,
# or provide the full path to the files.

@st.cache_resource
def load_cnn_model():
    """Loads the trained Keras CNN model."""
    try:
        # Replace 'your_cnn_model.h5' with the actual filename of your Keras model.
        model = tf.keras.models.load_model('mushroom_classifier_model.keras')
        return model
    except Exception as e:
        st.error(f"Error loading CNN model: {e}")
        return None

@st.cache_resource
def load_svm_model():
    """Loads the trained SVM model."""
    try:
        # Replace 'your_svm_model.joblib' with the actual filename of your SVM model.
        model = joblib.load('mushroom_svm_model.joblib')
        return model
    except Exception as e:
        st.error(f"Error loading SVM model: {e}")
        return None

# IMPORTANT: Define the class names your model was trained on.
# The order MUST exactly match the output of your model's prediction.
CLASS_NAMES = [
    "Agaricus xanthodermus",
    "Amanita augusta",
    "Amanita cirtina",
    "Armillaria mellea",
    "Boletus Edulis",
    "Clitocybe nuda",
    "Flammulina velutipes",
    "Hypholama lateritium",
    "Lactarius torminosus",
    "Leccinum scabrum",
]

# IMPORTANT: Define the toxicity information for each of your classes.
TOXICITY_INFO = {
    "Agaricus xanthodermus" : "Toxic",
    "Amanita augusta" : "Toxic",
    "Amanita cirtina" : "Toxic",
    "Armillaria mellea" : "Toxic",
    "Boletus Edulis" : "Toxic",
    "Clitocybe nuda" : "Safe",
    "Flammulina velutipes" : "Safe",
    "Hypholama lateritium" : "Safe",
    "Lactarius torminosus" : "Safe",
    "Leccinum scabrum" : "Safe",
}

# --- Prediction Function ---

def predict(model, image, model_type):
    """
    Preprocesses the image and returns prediction based on the model type.
    """
    # Open the image using PIL
    image = Image.open(io.BytesIO(image)).convert('RGB')

    # IMPORTANT: Change (128, 128) to your model's expected input size.
    target_size = (224, 224)
    image = image.resize(target_size)

    # Convert the image to a numpy array and normalize it
    image_array = np.array(image) / 255.0

    if model_type == 'CNN':
        # Add a batch dimension for the CNN model
        image_batch = np.expand_dims(image_array, axis=0)
        # Make a prediction
        predictions = model.predict(image_batch)
        predicted_index = np.argmax(predictions[0])
        confidence = np.max(predictions[0])
        return predicted_index, confidence

    elif model_type == 'SVM':
        # --- SVM Preprocessing ---
        # The SVM expects 8100 features, which corresponds to a 90x90 grayscale image.
        target_size = (90, 90)
        image = image.resize(target_size)
        image = image.convert('L') # Convert to grayscale
        image_array = np.array(image) / 255.0
        
        # Flatten the image array for the SVM model
        image_flattened = image_array.flatten().reshape(1, -1)
        
        # Make a prediction. The SVM model directly predicts the class name (string).
        predicted_species_name = model.predict(image_flattened)[0]
        
        # We need to find the integer index corresponding to this predicted name.
        try:
            predicted_index = CLASS_NAMES.index(predicted_species_name)
        except ValueError:
            # This is a safeguard in case the model predicts a class not in our list.
            st.error(f"Error: The model predicted a species ('{predicted_species_name}') that is not in the defined class list.")
            return None, None

        # Standard SVM .predict() doesn't give a confidence score, so we return None.
        return predicted_index, None


# --- Main Application ---
def main():
    st.title("🍄 Mushroom Classifier")
    st.sidebar.title("Model Selection")

    model_choice = st.sidebar.radio(
        "Choose a model for prediction:",
        ('-- Select a Model --', 'CNN (Keras)', 'SVM')
    )

    if model_choice == '-- Select a Model --':
        st.info("Welcome! Please select a model from the sidebar to begin classification.")
        st.markdown("""
        **Disclaimer:** This is a prototype and for educational purposes only.
        **Do not eat any mushroom based on this classification.** Always consult with an expert.
        """)

    elif model_choice in ['CNN (Keras)', 'SVM']:
        model_type = 'CNN' if 'CNN' in model_choice else 'SVM'
        st.header(f"Using {model_choice} Model")

        model = load_cnn_model() if model_type == 'CNN' else load_svm_model()

        if model is None:
            st.warning("The selected model could not be loaded. Please check the model file.")
            st.stop()

        uploaded_file = st.file_uploader(
            "Choose a mushroom image...",
            type=["jpg", "jpeg", "png"],
            key=f"{model_type}_uploader" # Unique key to prevent widget state issues
        )

        if uploaded_file is not None:
            bytes_data = uploaded_file.getvalue()
            st.image(bytes_data, caption='Uploaded Image.', use_column_width=True)

            with st.spinner('Analyzing the mushroom...'):
                try:
                    predicted_index, confidence = predict(model, bytes_data, model_type)
                    predicted_species = CLASS_NAMES[predicted_index]
                    toxicity = TOXICITY_INFO.get(predicted_species, "Unknown")

                    st.success("Classification Complete!")
                    st.markdown(f"### Predicted Species: **{predicted_species}**")

                    if confidence is not None:
                        st.markdown(f"### Confidence: **{confidence:.2%}**")

                    if "Poisonous" in toxicity or "Psychoactive" in toxicity:
                        st.error(f"### Toxicity: **{toxicity}** ☠️")
                    else:
                        st.success(f"### Toxicity: **{toxicity}** ✅")

                except Exception as e:
                    st.error(f"An error occurred during processing: {e}")

# Entry point for the script
if __name__ == '__main__':
    main()
